VARS = 'hostvars'

ID = 'id'
NAME = 'name'
SERVER_NAMES = 'balance_server_name'
SERVER_PORT = 'backend_port'
NODE_HOST = 'address'
NODE_ID = 'id'
NODE_PORT = 'port'
NODES_KEY = 'nodes'
REGION = 'region_name'
